# Generated by Django 3.0.8 on 2020-07-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200714_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='link',
            field=models.CharField(choices=[('Firma', 'core:about'), ('Oferta', 'core:offer'), ('Galeria', 'core:gallery'), ('Kontakt', 'core:contact')], default='', max_length=50),
        ),
    ]
