# Generated by Django 3.0.8 on 2020-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paragraph_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='link',
            field=models.CharField(choices=[('core:about', 'O Firmie'), ('core:offer', 'Oferta'), ('core:gallery', 'Galeria'), ('core:contact', 'Kontakt')], max_length=50),
        ),
    ]
