# Generated by Django 3.0.8 on 2020-07-17 11:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200715_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=20)),
                ('file', models.FileField(upload_to=core.models.content_file_name)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='link',
            field=models.CharField(blank=True, choices=[('/about', 'O Firmie'), ('/offer', 'Oferta'), ('/gallery', 'Galeria'), ('/contact', 'Kontakt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
