# Generated by Django 3.0.8 on 2020-07-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(upload_to='offers'),
        ),
    ]
