# Generated by Django 3.0.8 on 2020-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200724_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='amount',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
