# Generated by Django 3.0.8 on 2020-07-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_paragraph_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='image',
            field=models.FileField(upload_to='paragraph'),
        ),
    ]
