# Generated by Django 2.2.4 on 2019-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('main_page_carousel', 'main_page_carousel'), ('main_page_services', 'main_page_services'), ('footer', 'footer'), ('about_content', 'about_content'), ('about_main_content', 'about_main_content'), ('offer_main_content', 'offer_main_content'), ('contact', 'contact')], default='', max_length=100),
        ),
    ]
