# Generated by Django 2.2.4 on 2019-09-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anchor',
            field=models.CharField(choices=[('about', 'about'), ('offer', 'offer'), ('gallery', 'gallery')], default='', max_length=100),
        ),
    ]
