# Generated by Django 2.2.5 on 2019-09-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190908_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='main/static/documents/'),
        ),
    ]
