# Generated by Django 3.0.1 on 2019-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_anchor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='anchor',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('main_page', 'main_page'), ('about', 'about'), ('offer', 'offer'), ('contact', 'contact')], default='', max_length=100),
        ),
    ]
